### ISSUE TITLE
Didn't work

### ISSUE THREAD

**Issue by Leonkoithara** [aaronmjacobs/InitGL#1]
I believe cmakelists.txt is incorrect I got this error:
/home/leon/.Programming/opengl_glfw/TestApp/source/hello.cpp: In function ‘GLFWwindow* {anonymous}::initialize()’:
/home/leon/.Programming/opengl_glfw/TestApp/source/hello.cpp:32:25: error: ‘gladLoadGL’ was not declared in this scope
       int gladInitRes = gladLoadGL();
                         ^~~~~~~~~~
make[2]: *** [CMakeFiles/InitGL.dir/build.make:63: CMakeFiles/InitGL.dir/source/hello.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:69: CMakeFiles/InitGL.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
The GLFW documentation code doesn't work either
One of the glfw examples(boing.c) with #include <glad.h> worked with same makefile

**Comment by DRD7Bloo** [comment]
I can vouch for Leon, I get compiler errors when running the program.

**Comment by aaronhance** [comment]
Works just fine.

**Comment by TimKido** [comment]
Works fine for me too. I believe you didn't make your glad configuration correctly. I recommend you tu use the web portal. Do not forget to select Profile : 'Core' ; a version of gl ( > 3.3 if u want to use Core profile), and then click on 'ADD ALL' in the 'Extensions' part. I forget first time and had errors like yours.
